services:

  postgres:
    container_name: "postgres"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rello_test_task
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: "3s"
    networks:
      - services-network

networks:
  services-network:
    driver: bridge