output   = "./db/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "rello_test_task"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode = "disable"
  blacklist = ["migrations", "other"]