basePath: /
definitions:
  api.ApartmentResponse:
    properties:
      building_id:
        type: integer
      floor:
        type: integer
      id:
        type: integer
      number:
        type: string
      sq_meters:
        type: integer
    type: object
  api.BuildingResponse:
    properties:
      address:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  api.ErrResponse:
    properties:
      error:
        type: string
    type: object
  api.createApartmentRequest:
    properties:
      building_id:
        type: integer
      floor:
        type: integer
      number:
        type: string
      sq_meters:
        type: integer
    required:
    - building_id
    - floor
    - number
    - sq_meters
    type: object
  api.createBuildingRequest:
    properties:
      address:
        type: string
      name:
        type: string
    required:
    - address
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API to manage buildings and apartments
  title: Rello Test Task
  version: 0.0.1
paths:
  /apartments:
    get:
      description: Get all apartments
      operationId: get-apartments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.ApartmentResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Get apartments
      tags:
      - Apartment
    post:
      consumes:
      - application/json
      description: Create or update a apartment if already exists
      operationId: create-or-update-apartment
      parameters:
      - description: apartment entity related data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.createApartmentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ApartmentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Create or update a apartment
      tags:
      - Apartment
  /apartments/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific apartment by the specified id
      operationId: delete-apartment-by-id
      parameters:
      - description: the specific apartment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Delete apartment by id
      tags:
      - Apartment
    get:
      consumes:
      - application/json
      description: Get a specific apartment by the specified id
      operationId: get-apartment-by-id
      parameters:
      - description: the specific apartment id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ApartmentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Get apartment by id
      tags:
      - Apartment
  /apartments/building/{id}:
    get:
      consumes:
      - application/json
      description: Get all apartments by the specified building id
      operationId: get-apartment-by-building-id
      parameters:
      - description: the specific building id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ApartmentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Get all apartments by building id
      tags:
      - Apartment
  /buildings:
    get:
      description: Get all buildings
      operationId: get-buildings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.BuildingResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Get buildings
      tags:
      - Building
    post:
      consumes:
      - application/json
      description: Create or update a building if already exists
      operationId: create-or-update-building
      parameters:
      - description: building entity related data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.createBuildingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BuildingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Create or update a building
      tags:
      - Building
  /buildings/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific building by the specified id
      operationId: delete-building-by-id
      parameters:
      - description: the specific building id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Delete building by id
      tags:
      - Building
    get:
      consumes:
      - application/json
      description: Get a specific building by the specified id
      operationId: get-building-by-id
      parameters:
      - description: the specific building id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BuildingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Get building by id
      tags:
      - Building
swagger: "2.0"
